apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tiny-cliniq
  region: eu-central-1

nodeGroups:
    - name: backend-1
      instanceType: t2.micro
      desiredCapacity: 1
      volumeSize: 10
      ssh:
        publicKeyPath: ~/.ssh/id_rsa.pub
    - name: client-2
      instanceType: t2.micro
      desiredCapacity: 1
      volumeSize: 10
      ssh:
        publicKeyPath: ~/.ssh/id_rsa.pub

