db:
    image: postgres
    ports:
        - "5432:5432"
    env: 
        POSTGRES_PASSWORD=postgres
        POSTGRES_DB=tiny-cliniq
    volumes:
        -
backend:
    #image: clojure
    build: .
    command: lein run
    ports:
        - "80:80"
    volumes:
        - .:/usr/src/app
    links:
        - db
